const express = require('express')
const router = express.Router()
const userController = require("../../controllers/client/user.controller")
const userValidate = require("../../validates//client/user.validate")
router.get('/register',userController.register)
router.post('/register',userValidate.register,userController.postRegister)
router.get('/login',userController.login)
router.post('/login',userValidate.login,userController.postLogin)
router.get('/logout',userController.logout)
module.exports = router;